#!/bin/bash
# Run tika as a stand-alone application from the command line

# Default tika home: our directory
READLINK=$(if hash greadlink 2>/dev/null ; then echo greadlink; else echo readlink; fi)
TIKA_HOME=${TIKA_HOME:-$(dirname $($READLINK -f "$0"))}
TIKA_JAR=tika-app-1.23.jar

if [ -z "$1" ]; then
    echo "Usage: $0 file"
    exit 1
fi

# Download tika, if not present
if [ ! -e "$TIKA_HOME/$TIKA_JAR" ]; then
    # curl -L https://apache.rediris.es/tika/$TIKA_JAR --output "$TIKA_HOME/$TIKA_JAR"
    curl -L http://archive.apache.org/dist/tika/$TIKA_JAR --output "$TIKA_HOME/$TIKA_JAR"
fi

# Donwload sqlite, if not present
# Tika 1.19 depends on sqlite-jdbc 3.19.3 (this version exactly)
# Tika 1.20 depends on sqlite-jdbc 3.25.2 (this version exactly)
# Tika 1.21 depends on sqlite-jdbc 3.27.2.1 (this version exactly)
# Tika 1.23 depends on sqlite-jdbc 3.28.0 (this version exactly)
# Check dependencies in: {tika-app-XX.jar}/META-INF/maven/org.apache.tika/tika-parsers/pom.xml
SQLITE_VERSION="3.28.0"
SQLITE_JARFILE="sqlite-jdbc-$SQLITE_VERSION.jar"
if [ ! -e "$TIKA_HOME/$SQLITE_JARFILE" ]; then
    curl -L "https://search.maven.org/remotecontent?filepath=org/xerial/sqlite-jdbc/$SQLITE_VERSION/$SQLITE_JARFILE" --output "$TIKA_HOME/$SQLITE_JARFILE"
    # Alternate URL (the file has the same hash):
    # curl -L "https://bitbucket.org/xerial/sqlite-jdbc/downloads/$SQLITE_JARFILE" --output "$SQLITE_JARFILE"
fi

# Run tika on the file
java -classpath "$TIKA_HOME/$SQLITE_JARFILE:$TIKA_HOME/$TIKA_JAR" org.apache.tika.cli.TikaCLI -J -T "$1" 2>/dev/null | jq .
